### ISSUE TITLE
Where is gamebook.zip ?

### ISSUE THREAD

**Issue by Notsofastmatey** [alexa/skill-sample-nodejs-adventure-game#62]
When I get to the step

_Upload the zip file lambda/custom/gamebook.zip._

I can't find that file. Do I need to create it myself from the files in the _custom_ folder, adding in extra files for the dependencies?

Thanks,

Simon

**Comment by Notsofastmatey** [comment]
I created the zip with the correct dependencies myself using npm install.

**Comment by tekanoid** [comment]
Can you explain how/what you did?

**Comment by Notsofastmatey** [comment]
I was trying to do it all in the browser using the inline code editor, but that doesn't work. You have to install node.js on your local machine and follow the tutorials from there. I can't remember any more details - sorry!
