### ISSUE TITLE
Could not open file: /index.js

### ISSUE THREAD

**Issue by JofCla** [alexa/skill-sample-nodejs-adventure-game#65]
I ziped the custom files and uploaded it in the lambda function part but I have this message and it won't work. 
"The file index.js could not be found. Make sure your handler upholds the format: file-name.method."
I just uploaded the files and didn't chage any name.

Any idea of what I did wrong please? 
Thank you.

**Comment by franklin-lobb** [comment]
This most commonly happens when your files are inside a folder within the zip file rather than being in the root of the zip file.

**Comment by franklin-lobb** [comment]
@JofCla if you're still having problems, please reopen the issue.

**Comment by aoboaten1** [comment]
Having the same problem

**Comment by aaronskudder1** [comment]
I have the same problem.  I try put index.js in root and node modules in folder under root.  It still no work
