### ISSUE TITLE
What does this line do? const linksRegex = /\[\[([^\|\]]*)\|?([^\]]*)\]\]/g;

### ISSUE THREAD

**Issue by iam-Shashank** [alexa/skill-sample-nodejs-adventure-game#68]
`const linksRegex = /\[\[([^\|\]]*)\|?([^\]]*)\]\]/g;`
this is mentioned 14 times in index.js . what does it do?
https://github.com/alexa/skill-sample-nodejs-adventure-game/blob/master/lambda/custom/index.js

Is this similar to 
`displayableText = displayableText.replace(/<\/?[^>]+(>|$)/g, "");` What's the purpose of this line?
this was mentioned in step 6 of Challenges in https://github.com/alexa/skill-sample-nodejs-adventure-game/blob/master/instructions/5-customization.md

**Comment by gadgetchnnel** [comment]
That is used to find the links between passages, by finding anything which looks like either [_link text_] or [_link text_|_passage name_]  (the second format is what allows multiple links to go to the same passage or just for the passage name to not be the same as the link text).

**Comment by franklin-lobb** [comment]
@iam-Shashank did @gadgetchnnel answer your question?  If not, please reopen the issue.

**Comment by iam-Shashank** [comment]
Yeah, answered.
