### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by AlexaforMuggles** [alexa/skill-sample-nodejs-adventure-game#73]
Tried to clone it on npm. Got the following error: 
remote: Repository not found.
fatal: repository 'https://github.com/alexa/skill-sample-gamebook/' not found
Has it been replaced? If so what' the updated link? Couldn't find it on Google.

**Comment by error404notfound** [comment]
They havn't updated the docs yet I don't think

this worked.. 
git clone https://github.com/alexa/skill-sample-nodejs-adventure-game 

hope it works for youtoo!

**Comment by AlexaforMuggles** [comment]
Not sure what happened or why but tried again and it worked. Before it always asked me to sign in, now it just installed the files. Thanks for your help.
