### ISSUE TITLE
Request is not valid - Error parsing the requested content. Please validate the input

### ISSUE THREAD

**Issue by lhgustin** [alexa/skill-sample-nodejs-adventure-game#74]
I'm following the ask-cli steps from https://github.com/alexa/skill-sample-nodejs-adventure-game. I'm running `ask deploy` and got this message 

> Request is not valid - Error parsing the requested content. Please validate the input

More precisely : 

```
-------------------- Update Skill Project --------------------
Skill Id: amzn1.ask.skill.d1591672-6356-4e3d-863b-b0c54ee276ff
Skill deployment finished.
Call update-model error.
Error code: 400
{
  "message": "Request is not valid.",
  "violations": [
    {
      "message": "Error parsing the requested content. Please validate the input
."
    }
  ]
}
```

I solved the missing .ask/config issue by creating one like https://github.com/alexa/skill-sample-nodejs-audio-player/issues/80

Now I'm still stuck. `ask deploy --debug` gives me :  

[issue_debug.txt](https://github.com/alexa/skill-sample-nodejs-adventure-game/files/2016404/issue_debug.txt)

**Comment by franklin-lobb** [comment]
@lhgustin I'm taking a look.  Did you try to copy and paste the interaction model directly into the skill builder?  (Not saying that you should have to, just trying to eliminate causes).

**Comment by franklin-lobb** [comment]
The skill now successfully deploys via the ask deploy command.

**Comment by lhgustin** [comment]
I've just copied the model into the web interface .
Re-running `ask deploy` still gives me the error.
How did you fix the issue on your side ?

**Comment by lhgustin** [comment]
No lambda function seems to be created neither ...

**Comment by franklin-lobb** [comment]
You can see the exact changes [here](https://github.com/alexa/skill-sample-nodejs-adventure-game/commit/e5c1e7cce8820ca2e3485d62e87d6b4952ac05e6), however the issue was the id attribute was in the wrong place.  I also moved the invocationName to the top, but that was more aesthetic.

I believe the Lambda function is only created after the first successful skill deploy.
